<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\ClearCache\**" />
    <Compile Remove="Features\GetCache\**" />
    <Compile Remove="Features\GetOrCreateCache\**" />
    <EmbeddedResource Remove="Features\ClearCache\**" />
    <EmbeddedResource Remove="Features\GetCache\**" />
    <EmbeddedResource Remove="Features\GetOrCreateCache\**" />
    <None Remove="Features\ClearCache\**" />
    <None Remove="Features\GetCache\**" />
    <None Remove="Features\GetOrCreateCache\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Features\SetCache\SetCacheHandler.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CacheModule.Contract\CacheModule.Contract.csproj" />
  </ItemGroup>

</Project>
