global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Security.Cryptography;
global using System.Text;
global using System.Data;
global using System.Net;
global using System.Reflection;

global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Logging;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Routing;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Configuration;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.CodeAnalysis;


global using Asp.Versioning;
global using Carter;
global using Carter.OpenApi;
global using MediatR;
global using Swashbuckle.AspNetCore.SwaggerGen;
global using Swashbuckle.AspNetCore.SwaggerUI;

global using Infrastructure.DI;
global using Infrastructure.Extentions;
global using Infrastructure.Hangfier;
global using Infrastructure.MediatR;
global using Infrastructure.Messaging.Extentions;
global using Infrastructure.Contracts.CQRS;
global using Infrastructure.Exceptions;
global using Infrastructure.Data;
global using Infrastructure.Pagination;
global using Infrastructure.Data.Repository;
global using Infrastructure.Web.ApiResult;

global using IAMModule.Contract;
global using IAMModule.Contract.Responses;
global using IAMModule.Contract.Queries;
global using IAMModule.Contract.Commands;
global using IAMModule.Contract.Requests;
global using IAMModule.Contract.Models;
global using IAMModule.Entities;
global using IAMModule.Data.Context;
global using IAMModule.IAM.Authentications;
global using IAMModule.IAM.Exceptions;
global using IAMModule.IAM.Authorization;
global using IAMModule.Role.Exceptions;
global using IAMModule.Extensions;
