global using Test.Infrastructure.Requestes;
global using FluentAssertions;
global using Xunit.Abstractions;
global using Infrastructure.DateTimeHelpers.DateTimeProviders;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Moq;
global using Microsoft.Extensions.Logging;
global using Moq.Protected;