<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Modules\JobModules\**" />
    <Compile Remove="Modules\MutualFundModule\**" />
    <Compile Remove="Modules\SymbolModuleTest\Dtos\**" />
    <Compile Remove="Modules\SymbolModuleTest\IMEsTests\**" />
    <EmbeddedResource Remove="Modules\JobModules\**" />
    <EmbeddedResource Remove="Modules\MutualFundModule\**" />
    <EmbeddedResource Remove="Modules\SymbolModuleTest\Dtos\**" />
    <EmbeddedResource Remove="Modules\SymbolModuleTest\IMEsTests\**" />
    <None Remove="Modules\JobModules\**" />
    <None Remove="Modules\MutualFundModule\**" />
    <None Remove="Modules\SymbolModuleTest\Dtos\**" />
    <None Remove="Modules\SymbolModuleTest\IMEsTests\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MDF.API\MDF.API.csproj" />
    <ProjectReference Include="..\MDF.Test.Common\MDF.Test.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Update="BaseDataInDP.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ClearDb.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="DUMP2.sql">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\MofidXmls\Empty.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\MofidXmls\Fund_FixedIncome_XML_FixedIncome_20250429.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\MofidXmls\Fund_FixedIncome_XML_Leverage_20250504.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\MofidXmls\Fund_JointStock_XML_JointStock_20250428.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\MofidXmls\Fund_Leverage_XML_Leverage_20250428.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\MofidXmls\Fund_Mixed_XML_Mioxed_20250428.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\MofidXmls\Fund_11277_14040814.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\MofidXmls\HAMI.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\TadbirXmls\Fund_10630_14040520.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\TadbirXmls\Fund_12127_14040518.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\TadbirXmls\Fund_12196_14040518.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\TadbirXmls\Fund_12290_14040518.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\TadbirXmls\FundsXml.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\MofidXmls\FundsXml.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\MutualFundModuleTest\ExternalResourcesTest\ApiTest\TadbirXmls\Fund_FixedIncome_XML_Leverage_20250501.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\SymbolModuleTest\BoundTest\FeaturesTest\FixedIncomeProfitDailyUploadExcellFileTest\profitDaily.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Modules\TseTmcModuleTest\FeaturesTest\TseTmcSymbolCreateTest\DataFromTseTmc.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\TseTmcModuleTest\FeaturesTest\TseTmcSymbolUpdateTest\TseTmcSymboles1.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\TseTmcModuleTest\FeaturesTest\TseTmcSymbolUpdateTest\TseTmcSymboles2.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\TseTmcModuleTest\FeaturesTest\TseTmcSymbolUpdateTest\TseTmcSymboles3.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\TseTmcModuleTest\FeaturesTest\TseTmcSymbolUpdateTest\TseTmcSymboles4.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\TseTmcModuleTest\FeaturesTest\TseTmcSymbolUpdateTest\TseTmcSymboles5.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\TseTmcModuleTest\FeaturesTest\TseTmcSymbolUpdateTest\TseTmcSymboles6.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\TseTmcModuleTest\FeaturesTest\TseTmcSymbolUpdateTest\TseTmcSymboles7.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\TseTmcModuleTest\FeaturesTest\TseTmcSymbolUpdateTest\TseTmcSymboles9.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\TseTmcModuleTest\FeaturesTest\TseTmcSymbolUpdateTest\TseTmcSymbolesNoElement.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Modules\TseTmcModuleTest\FeaturesTest\TseTmcSymbolUpdateTest\TseTmcSymbolesOLD.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\TseTmcModuleTest\Dtos\" />
    <Folder Include="Modules\TseTmcModuleTest\Enumerations\" />
  </ItemGroup>

</Project>
